### ISSUE TITLE
netcoreapp3.1 Nuget.Framework could not be loaded on Linux. 

### ISSUE THREAD

**Issue by ErikFeeley** [yatli/fsharp-language-server#13]
To reproduce, create a new netcoreapp3.1 project on linux ( I am on Manjaro ). Open up vim / nvim. Project fails to load.

Interestingly loading a netcoreapp2.1 project works fine.

CocInfo details below.

`## versions

vim version: NVIM v0.4.3
node version: v13.7.0
coc.nvim version: 0.0.74-6700e7468d
term: xterm-kitty
platform: linux

## Messages
E492: Not an editor command: Coci
## Output channel: highlight

[Info  - 1:25:07 PM] Highlight server running in node v13.7.0

## Output channel: fsharp

Listening on stdin

Couldn't find System.ComponentModel.Composition.dll in /home/erik/.config/coc/extensions/coc-fsharp-data/server
Add workspace root /home/erik/_dev/personal-repos/FsharpTemp
output: 2.1.803 [/home/erik/dotnet/sdk]
output: 2.2.207 [/home/erik/dotnet/sdk]
output: 3.1.101 [/home/erik/dotnet/sdk]
dotnet pack folders: ["/home/erik/dotnet/packs"]
New configuration {
  "trace": {
    "server": "off"
  },
  "project": {
    "define": [],
    "otherFlags": [],
    "includeCompileBefore": false
  },
  "codelens": {
    "references": true
  },
  "analysis": {
    "unusedDeclaration": true
  }
}
analyzeLater: /home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj
No cracked project references Program.fs, looking at uncracked projects...
The text of FsharpTemp.fsproj contains the string 'Program.fs', cracking
Analyzing FsharpTemp.fsproj
msbuild: Build started.
msbuild: Project "FsharpTemp.fsproj" (Build target(s)):
msbuild: Building with tools version "Current".
msbuild: Target "_CheckForUnsupportedTargetFramework" skipped, due to false condition; ('$(_UnsupportedTargetFrameworkError)' == 'true') was evaluated as ('' == 'true').
msbuild: Target "_CollectTargetFrameworkForTelemetry" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
msbuild: Using "Telemetry" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
msbuild: Task "Telemetry"
msbuild: Done executing task "Telemetry".
msbuild: Done building target "_CollectTargetFrameworkForTelemetry" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForUnsupportedNETCoreVersion" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(_TargetFrameworkVersionWithoutV)' > '$(NETCoreAppMaximumVersion)') was evaluated as ('3.1' > '3.1').
msbuild: 
Done building target "_CheckForUnsupportedNETCoreVersion" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForUnsupportedCppNETCoreVersion" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETCoreApp' and '$(_TargetFrameworkVersionWithoutV)' < '3.1' and '$(Language)' == 'C++') was evaluated as ('.NETCoreApp' == '.NETCoreApp' and '3.1' < '3.1' and 'F#' == 'C++').
msbuild: Done building target "_CheckForUnsupportedCppNETCoreVersion" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForUnsupportedNETStandardVersion" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETStandard' And '$(NETStandardMaximumVersion)' != '') was evaluated as ('.NETCoreApp' == '.NETStandard' And '' != '').
msbuild: Target "_CheckForUnsupportedTargetFrameworkAndFeatureCombination" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETFramework') was evaluated as ('.NETCoreApp' == '.NETFramework').
msbuild: Target "_CheckForUnsupportedAppHostUsage" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(SelfContained)' == 'true' and '$(RuntimeIdentifier)' == '') was evaluated as ('false' == 'true' and '' == '').
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(SelfContained)' == 'true' and '$(UseAppHost)' != 'true') was evaluated as ('false' == 'true' and 'true' != 'true').
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(PublishSingleFile)' == 'true' and '$(RuntimeIdentifier)' == '') was evaluated as ('' == 'true' and '' == '').
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(PublishSingleFile)' == 'true' and '$(UseAppHost)' != 'true') was evaluated as ('' == 'true' and 'true' != 'true').
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(SelfContained)' != 'true' and '$(UseAppHost)' == 'true' and '$(_TargetFrameworkVersionWithoutV)' < '2.1') was evaluated as ('false' != 'true' and 'true' == 'true' and '3.1' < '2.1').
msbuild: Done building target "_CheckForUnsupportedAppHostUsage" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForMismatchingPlatform" skipped, due to false condition; ('$(RuntimeIdentifier)' != '' and '$(PlatformTarget)' != '') was evaluated as ('' != '' and '' != '').
msbuild: Target "_CheckForLanguageAndFeatureCombinationSupport" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_CheckForInvalidConfigurationAndPlatform" depends on it):
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(Language)' == 'C++' and $(OutputType) != 'library' and '$(TargetFrameworkIdentifier)' == '.NETCoreApp') was evaluated as ('F#' == 'C++' and Exe != 'library' and '.NETCoreApp' == '.NETCoreApp').
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(Language)' == 'C++' and $(EnableComHosting) == 'true') was evaluated as ('F#' == 'C++' and  == 'true').
msbuild: Done building target "_CheckForLanguageAndFeatureCombinationSupport" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForNETCoreSdkIsPreview" skipped, due to false condition; ( '$(_NETCoreSdkIsPreview)' == 'true' AND '$(SuppressNETCoreSdkPreviewMessage)' != 'true' ) was evaluated as ( 'false' == 'true' AND '' != 'true' ).
msbuild: Target "_GetProjectJsonPath" in file "/home/erik/dotnet/sdk/3.1.101/NuGet.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "_GetRestoreProjectStyle" depends on it):
msbuild: Task "GetRestoreProjectJsonPathTask" skipped, due to false condition; ( '$(RestoreProjectStyle)' == 'ProjectJson' OR '$(RestoreProjectStyle)' == '' ) was evaluated as ( 'PackageReference' == 'ProjectJson' OR 'PackageReference' == '' ).

msbuild: Done building target "_GetProjectJsonPath" in project "FsharpTemp.fsproj".
msbuild: Target "_CheckForUnsupportedNETStandardVersion" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETStandard' And '$(NETStandardMaximumVersion)' != '') was evaluated as ('.NETCoreApp' == '.NETStandard' And '' != '').
msbuild: Target "_CheckForUnsupportedTargetFrameworkAndFeatureCombination" skipped, due to false condition; ('$(TargetFrameworkIdentifier)' == '.NETFramework') was evaluated as ('.NETCoreApp' == '.NETFramework').
msbuild: Target "UpdateAspNetToFrameworkReference" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "ApplyImplicitVersions" depends on it):
msbuild: Using "CheckIfPackageReferenceShouldBeFrameworkReference" task from assembly "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll".
msbuild: Task "CheckIfPackageReferenceShouldBeFrameworkReference"

msbuild: Done executing task "CheckIfPackageReferenceShouldBeFrameworkReference".
msbuild: Task "NETSdkError" skipped, due to false condition; ('$(_ShouldRemoveAspNetCoreAll)' == 'true') was evaluated as ('False' == 'true').
msbuild: Task "CheckIfPackageReferenceShouldBeFrameworkReference"
msbuild: Done executing task "CheckIfPackageReferenceShouldBeFrameworkReference".
msbuild: Task "NETSdkWarning" skipped, due to false condition; ('$(_ShouldRemoveAspNetCoreApp)' == 'true') was evaluated as ('False' == 'true').
msbuild: Done building target "UpdateAspNetToFrameworkReference" in project "FsharpTemp.fsproj".
msbuild: Target "CheckForImplicitPackageReferenceOverrides" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "ApplyImplicitVersions" depends on it):
msbuild: Using "CheckForImplicitPackageReferenceOverrides" task from assembly "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll".
msbuild: Task "CheckForImplicitPackageReferenceOverrides"
msbuild: Done executing task "CheckForImplicitPackageReferenceOverrides".
msbuild: Done building target "CheckForImplicitPackageReferenceOverrides" in project "FsharpTemp.fsproj".
msbuild: Target "ApplyImplicitVersions" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "CollectPackageReferences" depends on it):
msbuild: Using "ApplyImplicitVersions" task from assembly "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll".
msbuild: Task "ApplyImplicitVersions"
msbuild: Done executing task "ApplyImplicitVersions".
msbuild: Done building target "ApplyImplicitVersions" in project "FsharpTemp.fsproj".
msbuild: Target "CheckForImplicitPackageReferenceOverrides" skipped. Previously built successfully.
msbuild: Target "ProcessFrameworkReferences" in file "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets" from project "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj" (target "CollectPackageReferences" depends on it):
msbuild: Using "CheckForDuplicateFrameworkReferences" task from assembly "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll".
msbuild: Task "CheckForDuplicateFrameworkReferences"
msbuild: Done executing task "CheckForDuplicateFrameworkReferences".
msbuild: Using "ProcessFrameworkReferences" task from assembly "/home/erik/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.1/Microsoft.NET.Build.Tasks.dll".
msbuild: Task "ProcessFrameworkReferences"
msbuild: The "ProcessFrameworkReferences" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.4.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'NuGet.Frameworks, Version=5.4.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

msbuild: Done executing task "ProcessFrameworkReferences" -- FAILED.
msbuild: Done building target "ProcessFrameworkReferences" in project "FsharpTemp.fsproj" -- FAILED.
msbuild: Done building project "FsharpTemp.fsproj" -- FAILED.
msbuild: Build FAILED.
Cracked FsharpTemp.fsproj in 7ms
Parsing /home/erik/_dev/personal-repos/FsharpTemp/obj/project.assets.json
Failed to build FsharpTemp.fsproj: Object reference not set to an instance of an object.
--------- Project references -----------------
---------- otherProjectReferences ----------------
----------- packageReferences ---------------
----------- directReferences ---------------
----------- systemReferences ---------------
----------- ConditionalCompilationDefines ---------------
----------- OtherCompilerFlags ---------------
--------------------------
/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj: 
  ProjectFileName: "/home/erik/_dev/personal-repos/FsharpTemp/FsharpTemp.fsproj"
  SourceFiles: [||]
  ReferencedProjects: []
  OtherOptions: [|"--noframework"|]
  LoadTime: 1/27/20 1:20:29 PM
  ExtraProjectInfo: <null>
  IsIncompleteTypeCheckEnvironment: false
  OriginalLoadReferences: []
  ExtraProjectInfo: <null>
  Stamp: <null>
  UnresolvedReferences: <null>
  UseScriptResolutionRules: false
No cracked project references Program.fs, looking at uncracked projects...`

**Comment by yatli** [comment]
Added netcoreapp3.1 and published a new version.
Use `fsharp.downloadLanguageServer` to pull that.

**Comment by ErikFeeley** [comment]
Thanks for the update! I cleared out coc-fsharp-data from my ./config/coc/extensions and re-installed the extension. When opening a netcoreapp3.1 or netcoreapp2.2 project I receive this error

`[coc.nvim] Installed extension: coc-fsharp
[coc.nvim] Error on active extension coc-fsharp: TypeError: Cannot read property 'browser_download_url' of undefined
    at LanguageServerProvider.<anonymous> (/home/erik/.config/coc/extensions/node_modules/coc-fsharp/node_modules/coc-utils/out/platform.js:88:42)
    at Generator.next (<anonymous>)
    at fulfilled (/home/erik/.config/coc/extensions/node_modules/coc-fsharp/node_modules/coc-utils/out/platform.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by yatli** [comment]
@ErikFeeley also see https://github.com/coc-extensions/coc-fsharp/issues/12, same problem.
Perhaps the auto download mechanism has failed.

**Comment by yatli** [comment]
Fixed. Please try again.

**Comment by ErikFeeley** [comment]
It works! Thanks so much! Fantomas works as well now which if I remember it did not run for me previously :)

**Comment by yatli** [comment]
Closing the issue now. Feel free to reopen if problem comes back.
