### ISSUE TITLE
Couldn't find System.ComponentModel.Composition.dll

### ISSUE THREAD

**Issue by PhilT** [yatli/fsharp-language-server#16]
Not sure if it's affecting anything as I'm still setting this thing up but I get the following error in CocInfo. Completion and some other functions still seem to be working.

```
Couldn't find System.ComponentModel.Composition.dll in C:\Users\Phil\.config\coc\extensions\coc-fsharp-data\server
```

Using Windows 10 with Neovim 0.4.3

vim version: NVIM v0.4.3
node version: v13.9.0
coc.nvim version: 0.0.78-fc983ce6dd
term: vtpcon
platform: win32

**Comment by yatli** [comment]
Can confirm. I have this problem on all platforms too -- doesn't seem to affect things.

**Comment by PhilT** [comment]
I guess something still has it as a dependency but it's no longer needed. I'll close. Thanks.
