### ISSUE TITLE
Language server can no longer find System.Reactive reference

### ISSUE THREAD

**Issue by PhilT** [yatli/fsharp-language-server#17]
Just started getting the following error:

```
[undefined 74: typecheck] [E] The type referenced through 
'System.Reactive.Subjects.ReplaySubject`1' is defined in an assembly that is not referenced. 
You must add a reference to assembly 'System.Reactive'.
```

The project cleans, builds and runs correctly.

[CocInfo.txt](https://github.com/coc-extensions/coc-fsharp/files/4525354/CocInfo.txt)

[project.assets.json.txt](https://github.com/coc-extensions/coc-fsharp/files/4525358/project.assets.json.txt)

**UPDATE**

I've now tried to reference and open the `System.Reactive` library directly (see my last comment) but the language server can't seem to find it. I've updated the title to better reflect the issue.

**Comment by PhilT** [comment]
Tried pinning System.Reactive to version 4.3.2 as version 4.4.1 hasn't been out long but that seems to not have any effect. Not sure what else to try.

**Comment by PhilT** [comment]
I tried following the advice here (https://github.com/coc-extensions/coc-fsharp/blob/master/CocSettings.md), however, I get "No .fsproj references..." for any file I open.

**Comment by PhilT** [comment]
I managed to get `.vim/coc-settings.json` configured correctly and it's building but I'm now getting the same errors as above:

`.vim/coc-settings.json` for a .NET Core 3.1 app:
```
{
    "fsharp.codelens.references": false,
    "fsharp.project.otherFlags": [
         "-o:..\\obj\\Debug\\netcoreapp3.1\\matter.dll",
         "-g",
         "--debug:portable",
         "--noframework",
         "--define:TRACE",
         "--define:DEBUG",
         "--define:NETCOREAPP",
         "--define:NETCOREAPP3_1",
         "--optimize-",
         "--tailcalls-",
         "--target:exe",
         "--nowarn:NU1603,NU1604,NU1605,NU1608",
         "--warn:3",
         "--warnaserror:3239,76",
         "--fullpaths",
         "--flaterrors",
         "--highentropyva-",
         "--targetprofile:netcore",
         "--nocopyfsharpcore",
         "--deterministic+",
         "--simpleresolution"
    ]
}
```

And just for clarification here is a screenshot of the error I'm seeing:

![Screenshot 2020-04-24 11 09 35](https://user-images.githubusercontent.com/34678/80201615-b1505d00-8624-11ea-9aec-3196134d6d09.png)

**Comment by PhilT** [comment]
I checked out an old version of coc-fsharp but still get the same issue. 

I used vim plug instead of CocInstall, cloned the repo, checked out the commit from March and ran `npm install`. 

`npm run compile` doesn't seem to work but I'm getting errors appearing so I think `npm install` was enough.

**Comment by PhilT** [comment]
A tad more info. Referring to the function directly, as in

`  let subject = new System.Reactive.Subjects.Subject<'a> ()`

gives the error `The type 'Reactive' is not defined`

but still compiles.

**Comment by yatli** [comment]
FSAC related and I believe this problem is automatically solved now.
