### ISSUE TITLE
support m1 macs

### ISSUE THREAD

**Issue by briandunn** [yatli/fsharp-language-server#23]
## steps to reproduce
1. `:CocInstall coc-fsharp`
2. `vim foo.fs`

### Expected
Extension loads and adds language server features

### actual
Error message "Platform not Supported" is printed

**Comment by briandunn** [comment]
I just opened this to draw attention to this pr:https://github.com/coc-extensions/coc-fsharp/pull/22, which fixed the issue on my machine. thanks @chendesheng

**Comment by yatli** [comment]
sorry it took soooooo long.... it's done now.
