### ISSUE TITLE
String interpolation syntax highlighting

### ISSUE THREAD

**Issue by wenLiangcan** [yatli/fsharp-language-server#24]
There's no syntax highlighting for string interpolation
![image](https://user-images.githubusercontent.com/1244181/134359126-adb8cd80-69f3-4ce0-9c02-9d9c0fc41b0b.png)

**Comment by yatli** [comment]
Seems FSAC is ready for this now: https://github.com/fsharp/FsAutoComplete/issues/710
So is coc.nvim: `:help coc-semantic-highlights`
Please consult `:help coc-config-semanticTokens` to enable semhl.

![image](https://user-images.githubusercontent.com/20684720/157240139-98cc8a97-172c-480a-8f17-64620c8bd766.png)
