### ISSUE TITLE
[Darwin] Couldn't find System.ComponentModel.Composition.dll in /Users/me/.config/coc/extensions/node_modules/coc-fsharp/out/server/osx.10.11-x64

### ISSUE THREAD

**Issue by lanza** [yatli/fsharp-language-server#7]
Not sure what that is, what it means or why it's not there, but that isn't being pulled into the OSX directory.

**Comment by yatli** [comment]
try 0.1.58 -- it's downloaded separately now

**Comment by lanza** [comment]
It worked! Thank you, yatli!
